config/routes.rb
Rails.application.routes.draw do
  resources :forums do
    resources :posts
  end

  resources :posts, only: [] do
    resources :comments, only: [:new, :create]
    resources :votes, only: [:create]
  end
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  authenticated :user do
    root to: 'forums#index', as: :authenticated_user_root
  end

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_rich_text :body
end

app/models/forum.rb
class Forum < ApplicationRecord
  belongs_to :user
  has_rich_text :description
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :forum
  has_rich_text :body
  has_many :comments

  def allowed_to_edit?(current_user)
    return true if current_user == user
    return true if current_user == forum.user
    false
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_uniqueness_of :username
  has_many :forums
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  def new
    @comment = @post.comments.new
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to [@post.forum, @post]
    else
      render :new
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: %i[ show edit update destroy ]

  # GET /forums or /forums.json
  def index
    @forums = Forum.all
  end

  # GET /forums/1 or /forums/1.json
  def show
  end

  # GET /forums/new
  def new
    @forum = Forum.new
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums or /forums.json
  def create
    @forum = current_user.forums.new(forum_params)

    respond_to do |format|
      if @forum.save
        format.html { redirect_to forum_url(@forum), notice: "Forum was successfully created." }
        format.json { render :show, status: :created, location: @forum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1 or /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to forum_url(@forum), notice: "Forum was successfully updated." }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1 or /forums/1.json
  def destroy
    @forum.destroy!

    respond_to do |format|
      format.html { redirect_to forums_url, notice: "Forum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def forum_params
      params.require(:forum).permit(:name, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_forum
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = @forum.posts.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @forum, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @forum, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to @forum, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_forum
      @forum = Forum.find(params[:forum_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = @forum.posts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id, :forum_id)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    case params[:vote]
    when "upvote"
      @post.update(score: @post.score + 1)
    when "downvote"
      @post.update(score: @post.score - 1)
    end
    redirect_to @post.forum
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/new.html.erb
<div class="max-w-5xl w-full mx-auto flex flex-col items-center mt-8">
  <h1 class="text-3xl"> Create new Comment </h1>
  <%= form_with model: [@post, @comment] do |f| %>
    <%= f.label :body %>
    <%= f.rich_text_area :body %>
    <%= f.submit %>
  <% end %>
</div>

app/views/forums/_form.html.erb
<%= form_with(model: forum, class: "contents") do |form| %>
  <% if forum.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

      <ul>
        <% forum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.rich_text_area :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/forums/_forum.html.erb
<%= link_to forum do %>
  <div id="<%= dom_id forum %>" class="bg-gray-300 py-2 px-4">
    <p class="my-2 text-3xl">
      <%= forum.name %>
    </p>

    <p class="my-2">
      <%= forum.description %>
    </p>
  </div>
<% end %>

app/views/forums/_post.html.erb
<div class="flex gap-3 w-full items-center">
  <div class="flex flex-col gap-4 mr-3">
    <%= link_to post_votes_path(post, vote: :upvote), data: { turbo_method: :post } do %>
      <div class="w-8 bg-gray-500 rounded-full flex justify-center items-center p-1 hover:bg-green-500">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-full">
          <path fill-rule="evenodd" d="M11.47 2.47a.75.75 0 0 1 1.06 0l7.5 7.5a.75.75 0 1 1-1.06 1.06l-6.22-6.22V21a.75.75 0 0 1-1.5 0V4.81l-6.22 6.22a.75.75 0 1 1-1.06-1.06l7.5-7.5Z" clip-rule="evenodd" />
        </svg>
      </div>
    <% end %>

    <%= link_to post_votes_path(post, vote: :downvote), data: { turbo_method: :post } do %>
      <div class="w-8 bg-gray-500 rounded-full flex justify-center items-center p-1 hover:bg-red-500">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-full">
          <path fill-rule="evenodd" d="M12 2.25a.75.75 0 0 1 .75.75v16.19l6.22-6.22a.75.75 0 1 1 1.06 1.06l-7.5 7.5a.75.75 0 0 1-1.06 0l-7.5-7.5a.75.75 0 1 1 1.06-1.06l6.22 6.22V3a.75.75 0 0 1 .75-.75Z" clip-rule="evenodd" />
        </svg>
      </div>
    <% end %>

  </div>

  <span class="text-2xl w-8 overflow-hidden">
    <%= post.score %>
  </span>

  <%= link_to [post.forum, post], class: "w-full" do %>
    <div class="w-full h-36 flex bg-gray-300 p-3">

      <div class="flex flex-col w-1/2">
        <span class="text-3xl"> <%= post.title %> </span>
        <span class="text-lg overflow-hidden"> <%= post.body.to_plain_text.first(50) %> </span>
      </div>
      <div class="flex flex-col w-1/2">
        <span class="text-lg"> Posted by <%= post.user.username %> </span>
        <span class="text-lg"> Posted <%= time_ago_in_words(post.created_at) %> ago </span>
      </div>
    </div>
  <% end %>
</div>

app/views/forums/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing forum</h1>

  <%= render "form", forum: @forum %>

  <%= link_to "Show this forum", @forum, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to forums", forums_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/forums/index.html.erb
<div class="max-w-5xl w-full mx-auto mt-8">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Forums</h1>
    <%= link_to "New forum", new_forum_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <br/>

  <div id="forums" class="min-w-full flex flex-col gap-4">
    <%= render @forums %>
  </div>
</div>

app/views/forums/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New forum</h1>

  <%= render "form", forum: @forum %>

  <%= link_to "Back to forums", forums_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/forums/show.html.erb
<div class="h-64 w-full bg-gray-500 flex flex-col justify-center items-center"> 
  <h1 class="text-7xl"> <%= @forum.name %> </h1>
  <br/>
  <p class="text-lg"> <%= @forum.description %> </p>
</div>

<div class="flex justify-end flex-wrap items-center gap-4 mt-4">
  <%= link_to "Create Post", new_forum_post_path(@forum), class: "bg-blue-500 text-blue-100 px-5 py-3 rounded-lg" %>
  <% if current_user == @forum.user %>
    <%= link_to "Edit this forum", edit_forum_path(@forum), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block">
      <%= button_to "Destroy this forum", forum_path(@forum), method: :delete, class: "rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  <% end %>
</div>

<div class="max-w-5xl w-full mx-auto mt-8 grid gap-4">
  <% @forum.posts.order(score: :desc).each do |post| %>
    <%= render "post", post: post %>
  <% end %>
</div>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<div class="w-full h-16 flex items-center justify-between p-3 bg-gray-700">
  <%= link_to "Home", "/", class: "text-xl text-gray-100" %>

  <% if current_user %>
    <div class="flex items-center gap-3">
      <span class="text-gray-100"> <%= current_user.username || "no username set" %> </span>
      <%= link_to "Sign Out", destroy_user_session_path, class: "bg-gray-300 text-gray-700 rounded-lg px-3 py-2", 
          data: { turbo_method: :delete } %>
    </div>
  <% end %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/alerts" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="w-full flex flex-col items-center">
  <h1 class="font-bold text-4xl">Reddit</h1>
  <p>Connect with other people in forums that you like</p>
  <br/>
  <%= link_to "Sign in", new_user_session_path, class: "bg-blue-500 text-blue-100 p-2 rounded-full w-32 text-center" %>
</div>

app/views/posts/_comment.html.erb
<div class="w-full ml-auto">
  <%= comment.body %>
  <span class="text-sm mt-2"> Posted by <%= comment.user.username %> </span>
  <hr/>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: [forum, post], class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.rich_text_area :body, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <h1 class="my-2 text-4xl">
    <%= post.title %>
  </h1>

   <p class="my-2 text-lg">
      Posted by <%= post.user.username %> To <%= post.forum.name %> Forum
    </p>


  <p class="my-2">
    <%= post.body %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this post", post, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this post", edit_post_path(post), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing post</h1>

  <%= render "form", post: @post, forum: @forum %>

  <%= link_to "Show this post", [@forum, @post], class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to Forum", @forum, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Posts</h1>
    <%= link_to "New post", new_post_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="posts" class="min-w-full">
    <%= render @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New post</h1>

  <%= render "form", post: @post, forum: @forum %>

  <%= link_to "Back to Forum", @forum, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/show.html.erb
<div class="mx-auto max-w-5xl w-full">
  <div class="mx-auto">
    <%= render @post %>

    <h2 class="text-xl mt-6"> Comments </h2>
    <div class="flex flex-col gap-4 mt-6">
      <% @post.comments.each do |comment| %>
        <%= render "comment", comment: comment %>
      <% end %>
    </div>
    
    <%= link_to "Comment", new_post_comment_path(@post), class: "bg-blue-500 text-blue-100 py-3 px-5 rounded-lg" %>

    <% if @post.allowed_to_edit?(current_user) %>
      <%= link_to "Edit this post", edit_forum_post_path(@forum, @post), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <div class="inline-block ml-2">
        <%= button_to "Destroy this post", [@forum, @post], method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      </div>
    <% end %>

    <%= link_to "Back to Forum", @forum, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>